import re


SKILL_SYNONYMS = {
    "ai": "Artificial Intelligence",
    "ml": "Machine Learning",
    "machine learning": "Machine Learning",
    "deep learning": "Deep Learning",
    "model evaluation": "Model Evaluation",
    "model benchmarking": "Model Benchmarking",
    "benchmarking": "Model Benchmarking",
    "computer vision": "Computer Vision",
    "cv": "Computer Vision",
    "opencv": "OpenCV",
    "image processing": "Image Processing",
    "object detection": "Object Detection",
    "image classification": "Image Classification",
    "segmentation": "Segmentation",
    "semantic segmentation": "Segmentation",
    "instance segmentation": "Segmentation",
    "medical imaging": "Medical Imaging",
    "monai": "MONAI",
    "yolo": "YOLO",
    "r-cnn": "R-CNN",
    "rcnn": "R-CNN",
    "faster r-cnn": "Faster R-CNN",
    "mask r-cnn": "Mask R-CNN",
    "ocr": "OCR",
    "document ai": "Document AI",
    "document intelligence": "Document AI",
    "tesseract": "Tesseract",
    "paddleocr": "PaddleOCR",
    "easyocr": "EasyOCR",
    "trocr": "TrOCR",
    "doctr": "DocTR",
    "omr": "OMR",
    "handwriting recognition": "Handwriting Recognition",
    "form recognition": "Form Recognition",
    "table recognition": "Table Recognition",
    "table structure recognition": "Table Recognition",
    "document extraction": "Document Extraction",
    "text extraction": "Text Extraction",
    "receipt extraction": "Receipt Extraction",
    "invoice extraction": "Invoice Extraction",
    "label extraction": "Label Extraction",
    "vial label extraction": "Label Extraction",
    "qr extraction": "QR Extraction",
    "document vqa": "Document VQA",
    "document visual question answering": "Document VQA",
    "image enhancement": "Image Enhancement",
    "real-esrgan": "Real-ESRGAN",
    "realesrgan": "Real-ESRGAN",
    "nlp": "NLP",
    "llm": "LLM",
    "llms": "LLM",
    "generative ai": "Generative AI",
    "genai": "Generative AI",
    "rag": "RAG",
    "langchain": "LangChain",
    "llamaindex": "LlamaIndex",
    "llama index": "LlamaIndex",
    "huggingface": "Hugging Face",
    "hugging face": "Hugging Face",
    "transformers": "Transformers",
    "vlm": "VLM",
    "vlms": "VLM",
    "vision language model": "Vision-Language Model",
    "vision-language model": "Vision-Language Model",
    "multimodal": "Multimodal AI",
    "multimodal ai": "Multimodal AI",
    "clip": "CLIP",
    "dino": "DINO",
    "blip": "BLIP",
    "vllm": "vLLM",
    "fine tuning": "Fine-tuning",
    "fine-tuning": "Fine-tuning",
    "lora": "LoRA",
    "qlora": "qLoRA",
    "prompt engineering": "Prompt Engineering",
    "vector db": "Vector Database",
    "vector database": "Vector Database",
    "pinecone": "Pinecone",
    "chroma": "Chroma",
    "faiss": "FAISS",
    "mlops": "MLOps",
    "llmops": "LLMOps",
    "mlflow": "MLflow",
    "model deployment": "Model Deployment",
    "model serving": "Model Serving",
    "inference pipeline": "Inference Pipeline",
    "inference optimization": "Inference Optimization",
    "latency optimization": "Latency Optimization",
    "cost optimization": "Cost Optimization",
    "system design": "System Design",
    "system architecture": "Software Architecture",
    "software architecture": "Software Architecture",
    "solution architecture": "Software Architecture",
    "backend architecture": "Backend Architecture",
    "api design": "API Design",
    "rest api design": "API Design",
    "distributed systems": "Distributed Systems",
    "distributed system": "Distributed Systems",
    "scalability": "Scalability",
    "scalable systems": "Scalability",
    "high scale systems": "High-scale Systems",
    "high-scale systems": "High-scale Systems",
    "microservices": "Microservices",
    "microservice": "Microservices",
    "product engineering": "Product Engineering",
    "product startup": "Product Startup",
    "startup experience": "Startup Experience",
    "0 to 1 product": "0-to-1 Product",
    "0-to-1 product": "0-to-1 Product",
    "zero to one product": "0-to-1 Product",
    "b2b saas": "B2B SaaS",
    "saas": "SaaS",
    "founder collaboration": "Founder Collaboration",
    "ownership": "Ownership",
    "technical leadership": "Technical Leadership",
    "tech leadership": "Technical Leadership",
    "tech lead": "Tech Lead",
    "code review": "Code Review",
    "code reviews": "Code Review",
    "engineering mentorship": "Engineering Mentorship",
    "mentorship": "Mentorship",
    "architecture review": "Architecture Review",
    "cloud architecture": "Cloud Architecture",
    "event driven architecture": "Event-driven Architecture",
    "event-driven architecture": "Event-driven Architecture",
    "observability": "Observability",
    "monitoring": "Monitoring",
    "sagemaker": "SageMaker",
    "vertex ai": "Vertex AI",
    "azure ml": "Azure ML",
    "bedrock": "Bedrock",
    "cloud run": "Cloud Run",
    "js": "JavaScript",
    "javascript": "JavaScript",
    "ts": "TypeScript",
    "typescript": "TypeScript",
    "php": "PHP",
    "c#": "C#",
    "c#.net": "C#",
    "c# .net": "C#",
    "c sharp": "C#",
    "dotnet": ".NET",
    ".net": ".NET",
    "net core": ".NET Core",
    ".net core": ".NET Core",
    "asp.net core": "ASP.NET Core",
    "asp .net core": "ASP.NET Core",
    "asp.net mvc": "ASP.NET MVC",
    "asp .net mvc": "ASP.NET MVC",
    "asp.net": "ASP.NET",
    "asp .net": "ASP.NET",
    "web api": "Web API",
    "asp.net web api": "ASP.NET Web API",
    "asp .net web api": "ASP.NET Web API",
    "entity framework": "Entity Framework",
    "linq": "LINQ",
    "ado.net": "ADO.NET",
    "ado .net": "ADO.NET",
    "t-sql": "T-SQL",
    "tsql": "T-SQL",
    "stored procedure": "Stored Procedures",
    "stored procedures": "Stored Procedures",
    "sql performance tuning": "SQL Performance Tuning",
    "database optimization": "Database Optimization",
    "pl/sql": "PL/SQL",
    "plsql": "PL/SQL",
    "kendo ui": "Kendo UI",
    "telerik": "Telerik",
    "telerik controls": "Telerik",
    "redis": "Redis",
    "distributed caching": "Distributed Caching",
    "open id connect": "OpenID Connect",
    "openid connect": "OpenID Connect",
    "sso": "SSO",
    "single sign on": "SSO",
    "single sign-on": "SSO",
    "azure devops": "Azure DevOps",
    "cursor": "Cursor",
    "devin": "Devin",
    "py": "Python",
    "python3": "Python",
    "reactjs": "React",
    "react.js": "React",
    "nextjs": "Next.js",
    "next.js": "Next.js",
    "vuejs": "Vue",
    "vue.js": "Vue",
    "nodejs": "Node.js",
    "node.js": "Node.js",
    "expressjs": "Express",
    "express.js": "Express",
    "mongodb": "MongoDB",
    "mongo db": "MongoDB",
    "mysql": "MySQL",
    "tailwind": "Tailwind CSS",
    "tailwind css": "Tailwind CSS",
    "bootstrap": "Bootstrap",
    "scss": "SCSS",
    "sass": "Sass",
    "es6": "ES6",
    "jsx": "JSX",
    "context api": "Context API",
    "zustand": "Zustand",
    "jotai": "Jotai",
    "recoil": "Recoil",
    "mobx": "MobX",
    "vite": "Vite",
    "webpack": "Webpack",
    "npm": "npm",
    "gitlab": "GitLab",
    "fetch": "Fetch",
    "axios": "Axios",
    "tanstack query": "TanStack Query",
    "react query": "TanStack Query",
    "responsive design": "Responsive Design",
    "mobile first": "Mobile-first Design",
    "mobile-first": "Mobile-first Design",
    "browser compatibility": "Browser Compatibility",
    "cross browser compatibility": "Cross-browser Compatibility",
    "cross-browser compatibility": "Cross-browser Compatibility",
    "ui ux": "UI/UX",
    "ui/ux": "UI/UX",
    "accessibility": "Accessibility",
    "a11y": "Accessibility",
    "chrome devtools": "Chrome DevTools",
    "devtools": "Chrome DevTools",
    "performance optimization": "Performance Optimization",
    "page speed": "Page Speed",
    "web vitals": "Web Vitals",
    "webvitals": "Web Vitals",
    "debugging": "Debugging",
    "browser debugging": "Browser Debugging",
    "code quality": "Code Quality",
    "material ui": "Material UI",
    "mui": "Material UI",
    "styled components": "Styled Components",
    "styled-components": "Styled Components",
    "storybook": "Storybook",
    "react testing library": "React Testing Library",
    "rtl": "React Testing Library",
    "seo": "SEO",
    "html5": "HTML",
    "css3": "CSS",
    "html": "HTML",
    "css": "CSS",
    "jwt": "JWT",
    "oauth": "OAuth",
    "auth": "Authentication",
    "authentication": "Authentication",
    "authorization": "Authorization",
    "rbac": "RBAC",
    "session": "Session Auth",
    "express session": "Session Auth",
    "express-session": "Session Auth",
    "firebase auth": "Firebase Auth",
    "auth0": "Auth0",
    "cognito": "AWS Cognito",
    "aws cognito": "AWS Cognito",
    "clerk": "Clerk Auth",
    "bcrypt": "Password Hashing",
    "password hashing": "Password Hashing",
    "spring security": "Spring Security",
    "token auth": "Token Auth",
    "access control": "Access Control",
    "mfa": "MFA",
    "multi factor authentication": "MFA",
    "openapi": "OpenAPI",
    "open api": "OpenAPI",
    "swagger": "Swagger",
    "crud": "CRUD",
    "api integration": "API Integration",
    "business logic": "Business Logic",
    "database design": "Database Design",
    "logging": "Logging",
    "error handling": "Error Handling",
    "validation": "Validation",
    "rate limiting": "Rate Limiting",
    "security": "Security",
    "git": "Git",
    "github": "GitHub",
    "github actions": "GitHub Actions",
    "ci/cd": "CI/CD",
    "cicd": "CI/CD",
    "postman": "Postman",
    "vercel": "Vercel",
    "netlify": "Netlify",
    "render": "Render",
    "heroku": "Heroku",
    "digitalocean": "DigitalOcean",
    "digital ocean": "DigitalOcean",
    "nginx": "Nginx",
    "vps": "VPS",
    "postgres": "PostgreSQL",
    "postgresql": "PostgreSQL",
    "mongoose": "Mongoose",
    "firebase": "Firebase",
    "firestore": "Firestore",
    "prisma": "Prisma",
    "sequelize": "Sequelize",
    "sql server": "SQL Server",
    "powerbi": "Power BI",
    "power bi": "Power BI",
    "tableau": "Tableau",
    "pytorch lightning": "PyTorch",
    "pytorch": "PyTorch",
    "tensorflow": "TensorFlow",
    "fast api": "FastAPI",
    "fastapi": "FastAPI",
    "flask": "Flask",
    "k8s": "Kubernetes",
    "kubernetes": "Kubernetes",
    "aws cloud": "AWS",
    "aws": "AWS",
    "amazon web services": "AWS",
    "sql": "SQL",
    "dax": "DAX",
    "eda": "EDA",
    "kpi": "KPI",
    "gcp": "Google Cloud",
    "azure cloud": "Azure",
    "attention to detail": "Attention to Detail",
    "analytical thinking": "Analytical Thinking",
    "problem solving": "Problem Solving",
    "communication": "Communication",
    "presentation": "Presentation",
    "salesforce": "Salesforce",
    "force.com": "Salesforce",
    "salesforce development": "Salesforce Development",
    "salesforce developer": "Salesforce Development",
    "apex": "Apex",
    "apex classes": "Apex",
    "apex triggers": "Apex",
    "lwc": "Lightning Web Components",
    "lightning web component": "Lightning Web Components",
    "lightning web components": "Lightning Web Components",
    "aura": "Aura Components",
    "aura component": "Aura Components",
    "aura components": "Aura Components",
    "visualforce": "Visualforce",
    "visual force": "Visualforce",
    "soql": "SOQL",
    "sosl": "SOSL",
    "salesforce flow": "Salesforce Flow",
    "flow builder": "Salesforce Flow",
    "salesforce cpq": "Salesforce CPQ",
    "cpq": "Salesforce CPQ",
    "sales cloud": "Sales Cloud",
    "service cloud": "Service Cloud",
    "experience cloud": "Experience Cloud",
    "community cloud": "Experience Cloud",
    "salesforce admin": "Salesforce Admin",
    "salesforce administrator": "Salesforce Admin",
    "data loader": "Data Loader",
    "sfdx": "SFDX",
    "salesforce dx": "SFDX",
    "rest api": "REST API",
    "restful": "REST API",
    "advanced excel": "Advanced Excel",
    "dashboard": "Dashboard",
    "dashboard creation": "Dashboard",
    "mis reporting": "MIS Reporting",
    "kpi": "KPI",
    "kpi reporting": "KPI Reporting",
    "business reporting": "Business Reporting",
    "reporting": "Reporting",
    "selenium webdriver": "Selenium",
    "selenium": "Selenium",
    "webdriver": "Selenium",
    "cypress": "Cypress",
    "playwright": "Playwright",
    "testng": "TestNG",
    "test ng": "TestNG",
    "junit": "JUnit",
    "pytest": "Pytest",
    "rest assured": "REST Assured",
    "restassured": "REST Assured",
    "rest-assured": "REST Assured",
    "soapui": "SoapUI",
    "soap ui": "SoapUI",
    "api testing": "API Testing",
    "manual testing": "Manual Testing",
    "automation testing": "Automation Testing",
    "test automation": "Automation Testing",
    "qa automation": "QA Automation",
    "regression testing": "Regression Testing",
    "smoke testing": "Smoke Testing",
    "sanity testing": "Sanity Testing",
    "functional testing": "Functional Testing",
    "integration testing": "Integration Testing",
    "end to end testing": "End-to-End Testing",
    "end-to-end testing": "End-to-End Testing",
    "e2e testing": "End-to-End Testing",
    "test cases": "Test Cases",
    "test case design": "Test Cases",
    "test plan": "Test Plan",
    "test scenarios": "Test Scenarios",
    "bug reporting": "Bug Reporting",
    "defect lifecycle": "Defect Life Cycle",
    "defect life cycle": "Defect Life Cycle",
    "stlc": "STLC",
    "sdlc": "SDLC",
    "jira": "Jira",
    "jenkins": "Jenkins",
    "gitlab ci": "GitLab CI",
    "cucumber": "Cucumber",
    "bdd": "BDD",
    "gherkin": "Gherkin",
    "jmeter": "JMeter",
    "appium": "Appium",
    "database testing": "Database Testing",
    "db validation": "Database Testing",
    "business analysis": "Business Analysis",
    "requirement gathering": "Requirement Gathering",
    "requirements gathering": "Requirement Gathering",
    "requirement analysis": "Requirement Analysis",
    "requirements analysis": "Requirement Analysis",
    "requirement documentation": "Requirement Documentation",
    "requirements documentation": "Requirement Documentation",
    "brd": "BRD",
    "frd": "FRD",
    "srs": "SRS",
    "user story": "User Stories",
    "user stories": "User Stories",
    "use case": "Use Cases",
    "use cases": "Use Cases",
    "acceptance criteria": "Acceptance Criteria",
    "functional specification": "Functional Specification",
    "functional specifications": "Functional Specification",
    "stakeholder management": "Stakeholder Management",
    "stakeholder coordination": "Stakeholder Management",
    "uat": "UAT",
    "user acceptance testing": "UAT",
    "change request": "Change Request",
    "gap analysis": "Gap Analysis",
    "process flow": "Process Flow",
    "workflow diagram": "Workflow Diagram",
    "business process mapping": "Business Process Mapping",
    "requirement traceability matrix": "Requirement Traceability Matrix",
    "rtm": "Requirement Traceability Matrix",
    "backlog grooming": "Backlog Grooming",
    "sprint planning": "Sprint Planning",
    "defect clarification": "Defect Clarification",
    "wireframe": "Wireframing",
    "wireframes": "Wireframing",
    "figma": "Figma",
    "balsamiq": "Balsamiq",
    "miro": "Miro",
    "lucidchart": "Lucidchart",
    "draw.io": "Draw.io",
    "ms visio": "MS Visio",
    "visio": "MS Visio",
}


TRANSFERABLE_GROUPS = [
    {"FastAPI", "Flask", "Django", "Express", "Spring Boot"},
    {".NET", ".NET Core", ".NET Framework", "ASP.NET", "ASP.NET Core", "ASP.NET MVC"},
    {"C#", "ASP.NET Core", "ASP.NET MVC", "Web API", "ASP.NET Web API", "Entity Framework", "LINQ", "ADO.NET", ".NET Core", ".NET Framework"},
    {"REST API", "RESTful APIs", "Web API", "ASP.NET Web API", "OpenAPI", "Swagger"},
    {"SQL", "SQL Server", "MS SQL", "T-SQL", "Stored Procedures", "SQL Performance Tuning", "Database Optimization", "PL/SQL"},
    {"PostgreSQL", "MySQL", "SQL Server", "Oracle", "SQLite"},
    {"Power BI", "Tableau", "Looker", "Qlik"},
    {"TensorFlow", "PyTorch", "Scikit-learn", "Keras"},
    {"AWS", "Azure", "Google Cloud"},
    {"React", "Angular", "Vue"},
    {"React", "Next.js", "Vue", "Angular"},
    {"Node.js", "Express", "Django", "FastAPI", "Laravel", "Spring Boot"},
    {"MongoDB", "Mongoose"},
    {"Firebase", "Firestore"},
    {"Docker", "Kubernetes", "CI/CD", "GitHub Actions"},
    {"JWT", "OAuth", "Authentication", "Authorization", "RBAC", "Session Auth", "Firebase Auth", "Auth0", "AWS Cognito", "Clerk Auth", "Spring Security", "Token Auth", "Access Control", "MFA", "Password Hashing"},
    {"Selenium", "Cypress", "Playwright"},
    {"Postman", "REST Assured", "Swagger", "SoapUI", "API Testing"},
    {"TestNG", "JUnit", "Pytest", "Cucumber", "BDD"},
]


SKILL_CATEGORIES = {
    "Python": "Programming",
    "JavaScript": "Programming",
    "TypeScript": "Programming",
    "Java": "Programming",
    "C#": "Programming",
    ".NET": "Backend",
    ".NET Core": "Backend",
    ".NET Framework": "Backend",
    "ASP.NET": "Backend",
    "ASP.NET Core": "Backend",
    "ASP.NET MVC": "Backend",
    "Web API": "Backend",
    "ASP.NET Web API": "Backend",
    "Entity Framework": "Backend",
    "LINQ": "Backend",
    "ADO.NET": "Backend",
    "SQL": "Data",
    "PostgreSQL": "Database",
    "MySQL": "Database",
    "FastAPI": "Backend",
    "Flask": "Backend",
    "Django": "Backend",
    "Express": "Backend",
    "Next.js": "Frontend",
    "Vue": "Frontend",
    "Angular": "Frontend",
    "HTML": "Frontend",
    "CSS": "Frontend",
    "SCSS": "Frontend",
    "Sass": "Frontend",
    "ES6": "Frontend",
    "JSX": "Frontend",
    "Tailwind CSS": "Frontend",
    "Bootstrap": "Frontend",
    "Material UI": "Frontend",
    "Styled Components": "Frontend",
    "Responsive Design": "Frontend",
    "Mobile-first Design": "Frontend",
    "Browser Compatibility": "Frontend",
    "Cross-browser Compatibility": "Frontend",
    "UI/UX": "Frontend",
    "Accessibility": "Frontend",
    "Context API": "Frontend",
    "Zustand": "Frontend",
    "Jotai": "Frontend",
    "Recoil": "Frontend",
    "MobX": "Frontend",
    "Vite": "Frontend",
    "Webpack": "Frontend",
    "npm": "Tools",
    "GitLab": "Tools",
    "Fetch": "Integration",
    "Axios": "Integration",
    "TanStack Query": "Frontend",
    "Chrome DevTools": "Tools",
    "Performance Optimization": "Frontend",
    "Page Speed": "Frontend",
    "Web Vitals": "Frontend",
    "Debugging": "Tools",
    "Browser Debugging": "Frontend",
    "Code Quality": "Frontend",
    "Storybook": "Frontend",
    "React Testing Library": "QA Automation",
    "SEO": "Frontend",
    "React": "Frontend",
    "Node.js": "Backend",
    "MongoDB": "Database",
    "Power BI": "Analytics",
    "Tableau": "Analytics",
    "Machine Learning": "AI/ML",
    "Deep Learning": "AI/ML",
    "Model Evaluation": "AI/ML",
    "Model Benchmarking": "AI/ML",
    "Computer Vision": "AI/ML",
    "OpenCV": "AI/ML",
    "Image Processing": "AI/ML",
    "Object Detection": "AI/ML",
    "Image Classification": "AI/ML",
    "Segmentation": "AI/ML",
    "Medical Imaging": "AI/ML",
    "OCR": "AI/ML",
    "Document AI": "AI/ML",
    "Tesseract": "AI/ML",
    "PaddleOCR": "AI/ML",
    "EasyOCR": "AI/ML",
    "TrOCR": "AI/ML",
    "DocTR": "AI/ML",
    "OMR": "AI/ML",
    "Handwriting Recognition": "AI/ML",
    "Form Recognition": "AI/ML",
    "Table Recognition": "AI/ML",
    "Document Extraction": "AI/ML",
    "Text Extraction": "AI/ML",
    "Receipt Extraction": "AI/ML",
    "Invoice Extraction": "AI/ML",
    "Label Extraction": "AI/ML",
    "QR Extraction": "AI/ML",
    "Document VQA": "AI/ML",
    "Image Enhancement": "AI/ML",
    "Real-ESRGAN": "AI/ML",
    "NLP": "AI/ML",
    "LLM": "AI/ML",
    "Generative AI": "AI/ML",
    "RAG": "AI/ML",
    "LangChain": "AI/ML",
    "LlamaIndex": "AI/ML",
    "Hugging Face": "AI/ML",
    "Transformers": "AI/ML",
    "VLM": "AI/ML",
    "Vision-Language Model": "AI/ML",
    "Multimodal AI": "AI/ML",
    "CLIP": "AI/ML",
    "DINO": "AI/ML",
    "BLIP": "AI/ML",
    "vLLM": "AI/ML",
    "Fine-tuning": "AI/ML",
    "LoRA": "AI/ML",
    "qLoRA": "AI/ML",
    "Prompt Engineering": "AI/ML",
    "Vector Database": "AI/ML",
    "Pinecone": "AI/ML",
    "Chroma": "AI/ML",
    "FAISS": "AI/ML",
    "MLOps": "AI/ML",
    "LLMOps": "AI/ML",
    "MLflow": "AI/ML",
    "Model Deployment": "AI/ML",
    "Model Serving": "AI/ML",
    "Inference Pipeline": "AI/ML",
    "Inference Optimization": "AI/ML",
    "Latency Optimization": "AI/ML",
    "Cost Optimization": "AI/ML",
    "TensorFlow": "AI/ML",
    "PyTorch": "AI/ML",
    "AWS": "Cloud",
    "Azure": "Cloud",
    "Docker": "DevOps",
    "Kubernetes": "DevOps",
    "Salesforce": "CRM",
    "Salesforce Development": "CRM",
    "Apex": "CRM",
    "Lightning Web Components": "CRM",
    "Aura Components": "CRM",
    "Visualforce": "CRM",
    "SOQL": "CRM",
    "SOSL": "CRM",
    "Salesforce Flow": "CRM",
    "Salesforce CPQ": "CRM",
    "Sales Cloud": "CRM",
    "Service Cloud": "CRM",
    "Experience Cloud": "CRM",
    "Salesforce Admin": "CRM",
    "Data Loader": "CRM",
    "SFDX": "CRM",
    "REST API": "Integration",
    "GraphQL": "Integration",
    "JWT": "Security",
    "OAuth": "Security",
    "Authentication": "Security",
    "Authorization": "Security",
    "RBAC": "Security",
    "Session Auth": "Security",
    "Firebase Auth": "Security",
    "Auth0": "Security",
    "AWS Cognito": "Security",
    "Spring Security": "Security",
    "Clerk Auth": "Security",
    "Password Hashing": "Security",
    "Token Auth": "Security",
    "Access Control": "Security",
    "MFA": "Security",
    "Git": "Tools",
    "GitHub": "Tools",
    "GitHub Actions": "DevOps",
    "Postman": "Tools",
    "Swagger": "Tools",
    "OpenAPI": "Tools",
    "CRUD": "Backend",
    "API Integration": "Integration",
    "Business Logic": "Backend",
    "Database Design": "Database",
    "Logging": "Backend",
    "Error Handling": "Backend",
    "Validation": "Backend",
    "Rate Limiting": "Security",
    "Security": "Security",
    "Vercel": "Cloud",
    "Netlify": "Cloud",
    "Render": "Cloud",
    "Heroku": "Cloud",
    "DigitalOcean": "Cloud",
    "Nginx": "DevOps",
    "VPS": "Cloud",
    "Firebase": "Database",
    "Firestore": "Database",
    "Mongoose": "Database",
    "Prisma": "Database",
    "Sequelize": "Database",
    "SQL Server": "Database",
    "MS SQL": "Database",
    "T-SQL": "Database",
    "PL/SQL": "Database",
    "Stored Procedures": "Database",
    "SQL Performance Tuning": "Database",
    "Database Optimization": "Database",
    "Kendo UI": "Frontend",
    "Telerik": "Frontend",
    "Redis": "Backend",
    "Distributed Caching": "Backend",
    "OpenID Connect": "Security",
    "SSO": "Security",
    "Azure DevOps": "DevOps",
    "Cursor": "Tools",
    "Devin": "Tools",
    "Advanced Excel": "Analytics",
    "Dashboard": "Analytics",
    "MIS Reporting": "Analytics",
    "KPI": "Analytics",
    "KPI Reporting": "Analytics",
    "Business Reporting": "Analytics",
    "Reporting": "Analytics",
    "Selenium": "QA Automation",
    "Cypress": "QA Automation",
    "Playwright": "QA Automation",
    "TestNG": "QA Framework",
    "JUnit": "QA Framework",
    "Pytest": "QA Framework",
    "REST Assured": "QA API Testing",
    "SoapUI": "QA API Testing",
    "API Testing": "QA API Testing",
    "Manual Testing": "QA",
    "Automation Testing": "QA Automation",
    "QA Automation": "QA Automation",
    "Regression Testing": "QA",
    "Smoke Testing": "QA",
    "Sanity Testing": "QA",
    "Functional Testing": "QA",
    "Integration Testing": "QA",
    "End-to-End Testing": "QA",
    "Test Cases": "QA",
    "Test Plan": "QA",
    "Test Scenarios": "QA",
    "Bug Reporting": "QA",
    "Defect Life Cycle": "QA",
    "STLC": "QA",
    "SDLC": "QA",
    "Jira": "Tools",
    "Jenkins": "DevOps",
    "GitLab CI": "DevOps",
    "Cucumber": "QA Framework",
    "BDD": "QA Framework",
    "Gherkin": "QA Framework",
    "JMeter": "Performance Testing",
    "Appium": "Mobile Testing",
    "Database Testing": "QA",
    "Business Analysis": "Business Analysis",
    "Requirement Gathering": "Business Analysis",
    "Requirement Analysis": "Business Analysis",
    "Requirement Documentation": "Business Analysis",
    "BRD": "Business Analysis",
    "FRD": "Business Analysis",
    "SRS": "Business Analysis",
    "User Stories": "Business Analysis",
    "Use Cases": "Business Analysis",
    "Acceptance Criteria": "Business Analysis",
    "Functional Specification": "Business Analysis",
    "Stakeholder Management": "Business Analysis",
    "UAT": "Business Analysis",
    "Change Request": "Business Analysis",
    "Gap Analysis": "Business Analysis",
    "Process Flow": "Business Analysis",
    "Workflow Diagram": "Business Analysis",
    "Business Process Mapping": "Business Analysis",
    "Requirement Traceability Matrix": "Business Analysis",
    "Backlog Grooming": "Agile",
    "Sprint Planning": "Agile",
    "Defect Clarification": "Business Analysis",
    "Wireframing": "Design",
    "Figma": "Design",
    "Balsamiq": "Design",
    "Miro": "Design",
    "Lucidchart": "Tools",
    "Draw.io": "Tools",
    "MS Visio": "Tools",
}


KNOWN_SKILL_PATTERNS = [
    ("Machine Learning", re.compile(r"\bmachine\s+learning\b|\bml\b", re.I)),
    ("Deep Learning", re.compile(r"\bdeep\s+learning\b|\bneural\s+networks?\b", re.I)),
    ("Model Evaluation", re.compile(r"\bmodel\s+evaluation\b|\bevaluat(?:ed|ion|ing)\s+models?\b", re.I)),
    ("Model Benchmarking", re.compile(r"\bmodel\s+benchmark(?:ing|s)?\b|\bbenchmark(?:ed|ing)?\s+models?\b", re.I)),
    ("Computer Vision", re.compile(r"\bcomputer\s+vision\b|\bimage\s+(?:recognition|understanding|analysis)\b", re.I)),
    ("OpenCV", re.compile(r"\bopencv\b", re.I)),
    ("Image Processing", re.compile(r"\bimage\s+processing\b|\bimage\s+enhancement\b", re.I)),
    ("Object Detection", re.compile(r"\bobject\s+detection\b|\byolo(?:v\d+)?\b|\br[-\s]?cnn\b|\bfaster\s+r[-\s]?cnn\b|\bmask\s+r[-\s]?cnn\b", re.I)),
    ("Image Classification", re.compile(r"\bimage\s+classification\b|\bclassifier\b", re.I)),
    ("Segmentation", re.compile(r"\b(?:semantic|instance)?\s*segmentation\b|\bct\s+segmentation\b", re.I)),
    ("Medical Imaging", re.compile(r"\bmedical\s+imaging\b|\bmri\b|\bretinal\b|\bultrasound\b|\boptical\s+coherence\s+tomography\b|\bmonai\b", re.I)),
    ("OCR", re.compile(r"\bocr\b|\boptical\s+character\s+recognition\b|\btext\s+extraction\s+from\s+images?\b", re.I)),
    ("Document AI", re.compile(r"\bdocument\s+(?:ai|intelligence|understanding|extraction)\b|\bscanned\s+documents?\b|\blayout\s+detection\b", re.I)),
    ("Tesseract", re.compile(r"\btesseract\b", re.I)),
    ("PaddleOCR", re.compile(r"\bpaddle\s*ocr\b|\bpaddleocr\b", re.I)),
    ("EasyOCR", re.compile(r"\beasy\s*ocr\b|\beasyocr\b", re.I)),
    ("TrOCR", re.compile(r"\btrocr\b", re.I)),
    ("DocTR", re.compile(r"\bdoctr\b", re.I)),
    ("OMR", re.compile(r"\bomr\b|\boptical\s+mark\s+recognition\b", re.I)),
    ("Handwriting Recognition", re.compile(r"\bhandwriting\s+recognition\b|\bhandwritten\s+text\b", re.I)),
    ("Form Recognition", re.compile(r"\bform\s+recognition\b|\bform\s+extraction\b", re.I)),
    ("Table Recognition", re.compile(r"\btable\s+(?:recognition|extraction|structure\s+recognition)\b", re.I)),
    ("Receipt Extraction", re.compile(r"\breceipt\s+extraction\b", re.I)),
    ("Invoice Extraction", re.compile(r"\binvoice\s+extraction\b", re.I)),
    ("Label Extraction", re.compile(r"\b(?:vial\s+)?label\s+extraction\b|\bdrug\s+name\b|\bdosage\s+extraction\b", re.I)),
    ("QR Extraction", re.compile(r"\bqr\s+(?:code\s+)?extraction\b|\blcd\s+panel\s+extraction\b", re.I)),
    ("Document VQA", re.compile(r"\bdocument\s+(?:vqa|visual\s+question\s+answering)\b", re.I)),
    ("Real-ESRGAN", re.compile(r"\breal[-\s]?esrgan\b", re.I)),
    ("NLP", re.compile(r"\bnlp\b|\bnatural\s+language\s+processing\b", re.I)),
    ("LLM", re.compile(r"\bllms?\b|\blarge\s+language\s+models?\b|\bgpt\b|\bllama\b|\bmistral\b|\bgemini\b|\bdeepseek\b", re.I)),
    ("Generative AI", re.compile(r"\bgenerative\s+ai\b|\bgenai\b", re.I)),
    ("RAG", re.compile(r"\brag\b|\bretrieval[-\s]?augmented\s+generation\b", re.I)),
    ("LangChain", re.compile(r"\blangchain\b", re.I)),
    ("LlamaIndex", re.compile(r"\bllama\s*index\b|\bllamaindex\b", re.I)),
    ("Hugging Face", re.compile(r"\bhugging\s*face\b|\bhuggingface\b", re.I)),
    ("Transformers", re.compile(r"\btransformers?\b", re.I)),
    ("VLM", re.compile(r"\bvlms?\b|\bvision[-\s]?language\s+models?\b", re.I)),
    ("Multimodal AI", re.compile(r"\bmultimodal\b|\bmulti[-\s]?modal\b", re.I)),
    ("CLIP", re.compile(r"\bclip\b", re.I)),
    ("DINO", re.compile(r"\bdino\b", re.I)),
    ("BLIP", re.compile(r"\bblip\b", re.I)),
    ("vLLM", re.compile(r"\bvllm\b", re.I)),
    ("Fine-tuning", re.compile(r"\bfine[-\s]?tun(?:e|ed|ing)\b", re.I)),
    ("LoRA", re.compile(r"\blora\b", re.I)),
    ("qLoRA", re.compile(r"\bqlora\b", re.I)),
    ("Prompt Engineering", re.compile(r"\bprompt(?:ing|s| engineering)\b", re.I)),
    ("Vector Database", re.compile(r"\bvector\s+(?:db|database)\b|\bembeddings?\b|\bpinecone\b|\bchroma\b|\bfaiss\b", re.I)),
    ("MLOps", re.compile(r"\bmlops\b|\bmodel\s+lifecycle\b", re.I)),
    ("LLMOps", re.compile(r"\bllmops\b", re.I)),
    ("MLflow", re.compile(r"\bmlflow\b", re.I)),
    ("Model Deployment", re.compile(r"\bmodel\s+deploy(?:ment|ed|ing)?\b|\bdeployed\s+models?\b", re.I)),
    ("Model Serving", re.compile(r"\bmodel\s+serving\b|\bserving\s+models?\b", re.I)),
    ("Inference Pipeline", re.compile(r"\binference\s+(?:pipeline|service|api)\b", re.I)),
    ("Inference Optimization", re.compile(r"\binference\s+optimization\b|\blatency\s+optimization\b|\bcost\s+optimization\b", re.I)),
    ("SageMaker", re.compile(r"\bsagemaker\b", re.I)),
    ("Vertex AI", re.compile(r"\bvertex\s+ai\b", re.I)),
    ("Azure ML", re.compile(r"\bazure\s+ml\b|\bazure\s+machine\s+learning\b", re.I)),
    ("Bedrock", re.compile(r"\bbedrock\b", re.I)),
    ("Salesforce", re.compile(r"\bsalesforce\b|\bforce\.com\b", re.I)),
    ("Salesforce Development", re.compile(r"\bsalesforce\s+(?:developer|development|engineering|engineer)\b", re.I)),
    ("Apex", re.compile(r"\bapex\b|\bapex\s+classes?\b|\bapex\s+triggers?\b", re.I)),
    ("Lightning Web Components", re.compile(r"\blightning\s+web\s+components?\b|\blwc\b", re.I)),
    ("Aura Components", re.compile(r"\baura\s+components?\b", re.I)),
    ("Visualforce", re.compile(r"\bvisual\s*force\b|\bvisualforce\b", re.I)),
    ("SOQL", re.compile(r"\bsoql\b", re.I)),
    ("SOSL", re.compile(r"\bsosl\b", re.I)),
    ("Salesforce Flow", re.compile(r"\b(?:salesforce\s+)?flows?\b|\bflow\s+builder\b", re.I)),
    ("Salesforce CPQ", re.compile(r"\bsalesforce\s+cpq\b|\bcpq\b", re.I)),
    ("Sales Cloud", re.compile(r"\bsales\s+cloud\b", re.I)),
    ("Service Cloud", re.compile(r"\bservice\s+cloud\b", re.I)),
    ("Experience Cloud", re.compile(r"\bexperience\s+cloud\b|\bcommunity\s+cloud\b", re.I)),
    ("Salesforce Admin", re.compile(r"\bsalesforce\s+admin(?:istrator)?\b", re.I)),
    ("Data Loader", re.compile(r"\bdata\s+loader\b", re.I)),
    ("SFDX", re.compile(r"\bsfdx\b|\bsalesforce\s+dx\b", re.I)),
    ("REST API", re.compile(r"\brest\s+api\b|\brestful\b", re.I)),
    ("RESTful APIs", re.compile(r"\brestful\s+apis?\b", re.I)),
    ("C#", re.compile(r"(?<!\w)c\s*#(?:\s*\.?\s*net)?(?!\w)|\bcsharp\b|\bc\s+sharp\b", re.I)),
    (".NET Core", re.compile(r"\b(?:\.net|dotnet|net)\s+core\b|\bcore\s+(?:\.net|dotnet)\b", re.I)),
    (".NET Framework", re.compile(r"\b(?:\.net|dotnet|net)\s+framework\b", re.I)),
    (".NET", re.compile(r"\b\.net\b|\bdotnet\b", re.I)),
    ("ASP.NET Core", re.compile(r"\basp\s*\.?\s*net\s+core\b|\baspnet\s+core\b", re.I)),
    ("ASP.NET MVC", re.compile(r"\basp\s*\.?\s*net\s+mvc\b|\baspnet\s+mvc\b", re.I)),
    ("ASP.NET Web API", re.compile(r"\basp\s*\.?\s*net\s+web\s+api\b|\baspnet\s+web\s+api\b", re.I)),
    ("ASP.NET", re.compile(r"\basp\s*\.?\s*net\b|\baspnet\b", re.I)),
    ("Web API", re.compile(r"\bweb\s+apis?\b|\bwebapi\b", re.I)),
    ("Entity Framework", re.compile(r"\bentity\s+framework\b|\bef\s+core\b", re.I)),
    ("LINQ", re.compile(r"\blinq\b", re.I)),
    ("ADO.NET", re.compile(r"\bado\s*\.?\s*net\b|\badonet\b", re.I)),
    ("GraphQL", re.compile(r"\bgraphql\b", re.I)),
    ("React", re.compile(r"\breact(?:\.js|js)?\b|\breact\s+native\b", re.I)),
    ("Next.js", re.compile(r"\bnext(?:\.js|js)?\b", re.I)),
    ("Vue", re.compile(r"\bvue(?:\.js|js)?\b", re.I)),
    ("Angular", re.compile(r"\bangular\b", re.I)),
    ("Node.js", re.compile(r"\bnode(?:\.js|js)?\b", re.I)),
    ("Express", re.compile(r"\bexpress(?:\.js|js)?\b", re.I)),
    ("Django", re.compile(r"\bdjango\b", re.I)),
    ("FastAPI", re.compile(r"\bfast\s*api\b|\bfastapi\b", re.I)),
    ("Laravel", re.compile(r"\blaravel\b", re.I)),
    ("Spring Boot", re.compile(r"\bspring\s+boot\b", re.I)),
    ("MongoDB", re.compile(r"\bmongo\s*db\b|\bmongodb\b", re.I)),
    ("MySQL", re.compile(r"\bmysql\b", re.I)),
    ("PostgreSQL", re.compile(r"\bpostgres(?:ql)?\b", re.I)),
    ("HTML", re.compile(r"\bhtml5?\b", re.I)),
    ("CSS", re.compile(r"\bcss3?\b", re.I)),
    ("Tailwind CSS", re.compile(r"\btailwind(?:\s+css)?\b", re.I)),
    ("Bootstrap", re.compile(r"\bbootstrap\b", re.I)),
    ("JWT", re.compile(r"\bjwt\b|\bjson\s+web\s+tokens?\b", re.I)),
    ("OAuth", re.compile(r"\boauth\b", re.I)),
    ("OpenID Connect", re.compile(r"\bopenid\s+connect\b|\bopen\s+id\s+connect\b|\boidc\b", re.I)),
    ("SSO", re.compile(r"\bsso\b|\bsingle\s+sign[-\s]?on\b", re.I)),
    ("Authentication", re.compile(r"\bauth(?:entication)?\b|\blogin\b|\bsign[-\s]?in\b", re.I)),
    ("Authorization", re.compile(r"\bauthori[sz]ation\b", re.I)),
    ("RBAC", re.compile(r"\brbac\b|\brole[-\s]?based\s+access\b", re.I)),
    ("Session Auth", re.compile(r"\bexpress[-\s]?session\b|\bsessions?\b", re.I)),
    ("Firebase Auth", re.compile(r"\bfirebase\s+auth\b", re.I)),
    ("Auth0", re.compile(r"\bauth0\b", re.I)),
    ("AWS Cognito", re.compile(r"\b(?:aws\s+)?cognito\b", re.I)),
    ("Clerk Auth", re.compile(r"\bclerk\b", re.I)),
    ("Spring Security", re.compile(r"\bspring\s+security\b", re.I)),
    ("Token Auth", re.compile(r"\btoken[-\s]?auth(?:entication)?\b|\baccess\s+tokens?\b|\brefresh\s+tokens?\b", re.I)),
    ("Access Control", re.compile(r"\baccess\s+control\b|\bsecure\s+access\b", re.I)),
    ("MFA", re.compile(r"\bmfa\b|\bmulti[-\s]?factor\s+authentication\b", re.I)),
    ("Password Hashing", re.compile(r"\bbcrypt\b|\bpassword\s+hash(?:ing)?\b", re.I)),
    ("Git", re.compile(r"\bgit\b", re.I)),
    ("GitHub", re.compile(r"\bgithub\b", re.I)),
    ("GitHub Actions", re.compile(r"\bgithub\s+actions\b", re.I)),
    ("Azure DevOps", re.compile(r"\bazure\s+devops\b", re.I)),
    ("Postman", re.compile(r"\bpostman\b", re.I)),
    ("Swagger", re.compile(r"\bswagger\b", re.I)),
    ("Selenium", re.compile(r"\bselenium(?:\s+web\s*driver|\s+webdriver)?\b|\bwebdriver\b", re.I)),
    ("Cypress", re.compile(r"\bcypress\b", re.I)),
    ("Playwright", re.compile(r"\bplaywright\b", re.I)),
    ("TestNG", re.compile(r"\btest\s*ng\b|\btestng\b", re.I)),
    ("JUnit", re.compile(r"\bjunit\b", re.I)),
    ("Pytest", re.compile(r"\bpytest\b|\bpy\.?test\b", re.I)),
    ("REST Assured", re.compile(r"\brest[-\s]?assured\b|\brestassured\b", re.I)),
    ("SoapUI", re.compile(r"\bsoap\s*ui\b|\bsoapui\b", re.I)),
    ("API Testing", re.compile(r"\bapi\s+testing\b|\brest\s+api\s+testing\b|\bweb\s+services?\s+testing\b", re.I)),
    ("Manual Testing", re.compile(r"\bmanual\s+testing\b", re.I)),
    ("Automation Testing", re.compile(r"\bautomation\s+testing\b|\btest\s+automation\b", re.I)),
    ("QA Automation", re.compile(r"\bqa\s+automation\b|\bsdet\b|\bsoftware\s+development\s+engineer\s+in\s+test\b", re.I)),
    ("Regression Testing", re.compile(r"\bregression\s+testing\b", re.I)),
    ("Smoke Testing", re.compile(r"\bsmoke\s+testing\b", re.I)),
    ("Sanity Testing", re.compile(r"\bsanity\s+testing\b", re.I)),
    ("Functional Testing", re.compile(r"\bfunctional\s+testing\b", re.I)),
    ("Integration Testing", re.compile(r"\bintegration\s+testing\b", re.I)),
    ("End-to-End Testing", re.compile(r"\bend[-\s]?to[-\s]?end\s+testing\b|\be2e\s+testing\b", re.I)),
    ("Test Cases", re.compile(r"\btest\s+cases?\b|\btest\s+case\s+design\b", re.I)),
    ("Test Plan", re.compile(r"\btest\s+plans?\b", re.I)),
    ("Test Scenarios", re.compile(r"\btest\s+scenarios?\b", re.I)),
    ("Bug Reporting", re.compile(r"\bbug\s+reporting\b|\bdefect\s+reporting\b", re.I)),
    ("Defect Life Cycle", re.compile(r"\bdefect\s+life\s+cycle\b|\bbug\s+life\s+cycle\b|\bdefect\s+lifecycle\b", re.I)),
    ("STLC", re.compile(r"\bstlc\b|\bsoftware\s+testing\s+life\s+cycle\b", re.I)),
    ("SDLC", re.compile(r"\bsdlc\b|\bsoftware\s+development\s+life\s+cycle\b", re.I)),
    ("Jira", re.compile(r"\bjira\b", re.I)),
    ("Jenkins", re.compile(r"\bjenkins\b", re.I)),
    ("GitLab CI", re.compile(r"\bgitlab\s+ci\b", re.I)),
    ("Cucumber", re.compile(r"\bcucumber\b", re.I)),
    ("BDD", re.compile(r"\bbdd\b|\bbehavior[-\s]?driven\s+development\b", re.I)),
    ("Gherkin", re.compile(r"\bgherkin\b", re.I)),
    ("JMeter", re.compile(r"\bjmeter\b", re.I)),
    ("Appium", re.compile(r"\bappium\b", re.I)),
    ("Database Testing", re.compile(r"\bdatabase\s+testing\b|\bdb\s+validation\b|\bdatabase\s+validation\b", re.I)),
    ("Business Analysis", re.compile(r"\bbusiness\s+analys(?:is|t)\b|\bba\s+concepts?\b", re.I)),
    ("Requirement Gathering", re.compile(r"\brequirements?\s+gathering\b|\bgather(?:ed|ing)?\s+business\s+requirements?\b", re.I)),
    ("Requirement Analysis", re.compile(r"\brequirements?\s+analysis\b|\banaly[sz](?:ed|e|ing)\s+requirements?\b", re.I)),
    ("Requirement Documentation", re.compile(r"\brequirements?\s+documentation\b|\bdocument(?:ed|ing)?\s+(?:business\s+)?requirements?\b", re.I)),
    ("BRD", re.compile(r"\bbrd\b|\bbusiness\s+requirements?\s+documents?\b", re.I)),
    ("FRD", re.compile(r"\bfrd\b|\bfunctional\s+requirements?\s+documents?\b", re.I)),
    ("SRS", re.compile(r"\bsrs\b|\bsoftware\s+requirements?\s+specification\b", re.I)),
    ("User Stories", re.compile(r"\buser\s+stor(?:y|ies)\b", re.I)),
    ("Use Cases", re.compile(r"\buse\s+cases?\b", re.I)),
    ("Acceptance Criteria", re.compile(r"\bacceptance\s+criteria\b", re.I)),
    ("Functional Specification", re.compile(r"\bfunctional\s+specifications?\b|\bfunctional\s+requirements?\b", re.I)),
    ("Stakeholder Management", re.compile(r"\bstakeholders?\b|\bstakeholder\s+(?:management|coordination|meetings?)\b", re.I)),
    ("UAT", re.compile(r"\buat\b|\buser\s+acceptance\s+testing\b", re.I)),
    ("Change Request", re.compile(r"\bchange\s+requests?\b", re.I)),
    ("Gap Analysis", re.compile(r"\bgap\s+analysis\b", re.I)),
    ("Process Flow", re.compile(r"\bprocess\s+flows?\b", re.I)),
    ("Workflow Diagram", re.compile(r"\bworkflow\s+diagrams?\b|\bworkflow\b", re.I)),
    ("Business Process Mapping", re.compile(r"\bbusiness\s+process\s+mapping\b|\bprocess\s+mapping\b", re.I)),
    ("Requirement Traceability Matrix", re.compile(r"\brequirements?\s+traceability\s+matrix\b|\brtm\b", re.I)),
    ("Backlog Grooming", re.compile(r"\bbacklog\s+grooming\b", re.I)),
    ("Sprint Planning", re.compile(r"\bsprint\s+planning\b", re.I)),
    ("Defect Clarification", re.compile(r"\bdefect\s+clarification\b|\bdefect\s+triage\b", re.I)),
    ("Wireframing", re.compile(r"\bwireframes?\b|\bwireframing\b", re.I)),
    ("Figma", re.compile(r"\bfigma\b", re.I)),
    ("Balsamiq", re.compile(r"\bbalsamiq\b", re.I)),
    ("Miro", re.compile(r"\bmiro\b", re.I)),
    ("Lucidchart", re.compile(r"\blucidchart\b", re.I)),
    ("Draw.io", re.compile(r"\bdraw\.io\b", re.I)),
    ("MS Visio", re.compile(r"\b(?:ms\s+)?visio\b", re.I)),
    ("OpenAPI", re.compile(r"\bopen\s*api\b|\bopenapi\b", re.I)),
    ("CRUD", re.compile(r"\bcrud\b|\bcreate,\s*read,\s*update,\s*delete\b", re.I)),
    ("API Integration", re.compile(r"\bapi\s+integration\b|\bintegrat(?:ed|ion)\s+(?:third[-\s]?party\s+)?apis?\b", re.I)),
    ("Fetch", re.compile(r"\bfetch\s*(?:api)?\b", re.I)),
    ("Axios", re.compile(r"\baxios\b", re.I)),
    ("TanStack Query", re.compile(r"\btanstack\s+query\b|\breact\s+query\b", re.I)),
    ("Context API", re.compile(r"\bcontext\s+api\b", re.I)),
    ("Zustand", re.compile(r"\bzustand\b", re.I)),
    ("Jotai", re.compile(r"\bjotai\b", re.I)),
    ("Recoil", re.compile(r"\brecoil\b", re.I)),
    ("MobX", re.compile(r"\bmobx\b", re.I)),
    ("Vite", re.compile(r"\bvite\b", re.I)),
    ("Webpack", re.compile(r"\bwebpack\b", re.I)),
    ("npm", re.compile(r"\bnpm\b", re.I)),
    ("GitLab", re.compile(r"\bgitlab\b", re.I)),
    ("Responsive Design", re.compile(r"\bresponsive\s+(?:web\s+)?design\b|\bresponsive\s+(?:ui|interfaces?|layouts?)\b", re.I)),
    ("Mobile-first Design", re.compile(r"\bmobile[-\s]?first\b", re.I)),
    ("Browser Compatibility", re.compile(r"\bbrowser\s+compatibility\b|\bcross[-\s]?browser\b", re.I)),
    ("UI/UX", re.compile(r"\bui\s*/\s*ux\b|\bui\s+ux\b|\buser\s+experience\b", re.I)),
    ("Accessibility", re.compile(r"\baccessibility\b|\ba11y\b|\bwcag\b", re.I)),
    ("Chrome DevTools", re.compile(r"\bchrome\s+devtools\b|\bdevtools\b", re.I)),
    ("Performance Optimization", re.compile(r"\bperformance\s+optimization\b|\boptimi[sz](?:e|ed|ing)\s+(?:frontend|front[-\s]?end|web|page|application)\b", re.I)),
    ("Page Speed", re.compile(r"\bpage\s+speed\b", re.I)),
    ("Web Vitals", re.compile(r"\bweb\s*vitals\b|\bwebvitals\b", re.I)),
    ("Debugging", re.compile(r"\bdebug(?:ging|ged)?\b", re.I)),
    ("Browser Debugging", re.compile(r"\bbrowser\s+debug(?:ging)?\b", re.I)),
    ("Code Quality", re.compile(r"\bcode\s+quality\b|\bclean\s+code\b", re.I)),
    ("Material UI", re.compile(r"\bmaterial\s+ui\b|\bmui\b", re.I)),
    ("Styled Components", re.compile(r"\bstyled[-\s]?components\b", re.I)),
    ("Storybook", re.compile(r"\bstorybook\b", re.I)),
    ("React Testing Library", re.compile(r"\breact\s+testing\s+library\b", re.I)),
    ("SEO", re.compile(r"\bseo\b|\bsearch\s+engine\s+optimization\b", re.I)),
    ("Business Logic", re.compile(r"\bbusiness\s+logic\b", re.I)),
    ("Database Design", re.compile(r"\bdatabase\s+(?:design|schema|schemas|model(?:ing)?)\b|\bdata\s+model(?:ing)?\b", re.I)),
    ("Logging", re.compile(r"\blogging\b|\blogs?\b", re.I)),
    ("Error Handling", re.compile(r"\berror\s+handling\b|\bexception\s+handling\b", re.I)),
    ("Validation", re.compile(r"\bvalidation\b|\bvalidations\b", re.I)),
    ("Rate Limiting", re.compile(r"\brate\s+limiting\b", re.I)),
    ("Security", re.compile(r"\bsecurity\b|\bsecure\b", re.I)),
    ("Vercel", re.compile(r"\bvercel\b", re.I)),
    ("Netlify", re.compile(r"\bnetlify\b", re.I)),
    ("Render", re.compile(r"\brender\b", re.I)),
    ("Heroku", re.compile(r"\bheroku\b", re.I)),
    ("DigitalOcean", re.compile(r"\bdigital\s*ocean\b|\bdigitalocean\b", re.I)),
    ("Nginx", re.compile(r"\bnginx\b", re.I)),
    ("VPS", re.compile(r"\bvps\b|\bvirtual\s+private\s+server\b", re.I)),
    ("CI/CD", re.compile(r"\bci\s*/\s*cd\b|\bcicd\b|\bcontinuous\s+integration\b", re.I)),
    ("Redis", re.compile(r"\bredis\b", re.I)),
    ("Distributed Caching", re.compile(r"\bdistributed\s+cach(?:e|ing)\b", re.I)),
    ("Microservices", re.compile(r"\bmicroservices?\b", re.I)),
    ("Kendo UI", re.compile(r"\bkendo(?:\s+ui)?\b", re.I)),
    ("Telerik", re.compile(r"\btelerik(?:\s+controls?)?\b", re.I)),
    ("Stored Procedures", re.compile(r"\bstored\s+procedures?\b|\bsprocs?\b", re.I)),
    ("SQL Performance Tuning", re.compile(r"\bsql\s+performance\s+tuning\b|\bperformance\s+tuning\b|\bquery\s+optimization\b", re.I)),
    ("Database Optimization", re.compile(r"\bdatabase\s+optimization\b|\bdb\s+optimization\b", re.I)),
    ("T-SQL", re.compile(r"\bt[-\s]?sql\b|\btsql\b", re.I)),
    ("PL/SQL", re.compile(r"\bpl\s*/\s*sql\b|\bplsql\b", re.I)),
    ("Cursor", re.compile(r"\bcursor\b", re.I)),
    ("Devin", re.compile(r"\bdevin\b", re.I)),
    ("Linux", re.compile(r"\blinux\b", re.I)),
    ("Firebase", re.compile(r"\bfirebase\b", re.I)),
    ("Firestore", re.compile(r"\bfirestore\b", re.I)),
    ("Mongoose", re.compile(r"\bmongoose\b", re.I)),
    ("Prisma", re.compile(r"\bprisma\b", re.I)),
    ("Sequelize", re.compile(r"\bsequelize\b", re.I)),
    ("SQL Server", re.compile(r"\bsql\s+server\b", re.I)),
    ("MS SQL", re.compile(r"\bms\s+sql\b|\bmssql\b", re.I)),
    ("Google Apps Script", re.compile(r"\bgoogle\s+apps?\s+script\b", re.I)),
    ("Power Query", re.compile(r"\bpower\s+query\b", re.I)),
    ("Power BI", re.compile(r"\bpower\s*bi\b|\bpowerbi\b", re.I)),
    ("Advanced Excel", re.compile(r"\badvanced\s+excel\b|\bpivot\s+tables?\b|\bvlookups?\b|\bxlookups?\b|\bmacros?\b|\bvba\b", re.I)),
    ("Excel", re.compile(r"\b(?:(?:ms|microsoft)\s+)?excel\b", re.I)),
    ("SQL", re.compile(r"\bsql(?:\s+queries|\s+query)?\b", re.I)),
    ("Python", re.compile(r"\bpython\b", re.I)),
    ("Pandas", re.compile(r"\bpandas\b", re.I)),
    ("NumPy", re.compile(r"\bnumpy\b|\bnum\s*py\b", re.I)),
    ("Matplotlib", re.compile(r"\bmatplotlib\b", re.I)),
    ("Seaborn", re.compile(r"\bseaborn\b", re.I)),
    ("Tableau", re.compile(r"\btableau\b", re.I)),
    ("DAX", re.compile(r"\bdax\b", re.I)),
    ("JavaScript", re.compile(r"\bjava\s*script\b|\bjavascript\b", re.I)),
    ("Statistics", re.compile(r"\bstatistics?\b|\bstatistical\b|\bpredictive\s+analytics?\b|\bspss\b|\bsas\b", re.I)),
    ("EDA", re.compile(r"\beda\b|\bexploratory\s+data\s+analysis\b", re.I)),
    ("Data Cleaning", re.compile(r"\bdata\s+clean(?:ing)?\b|\bdata\s+validat(?:e|ion|ing)\b|\breconciliation\b|\bremediation\b", re.I)),
    ("Data Extraction", re.compile(r"\bdata\s+extract(?:ion)?\b|\bextract(?:ed|ion)?\b", re.I)),
    ("Data Visualization", re.compile(r"\bdata\s+visuali[sz]ation\b|\bdashboard(?:ing)?\b", re.I)),
    ("Dashboard", re.compile(r"\bdashboards?\b|\bdashboard\s+creation\b", re.I)),
    ("MIS Reporting", re.compile(r"\bmis\s+report(?:ing|s)?\b", re.I)),
    ("KPI Reporting", re.compile(r"\bkpi\s+report(?:ing|s)?\b", re.I)),
    ("KPI", re.compile(r"\bkpis?\b", re.I)),
    ("Business Reporting", re.compile(r"\bbusiness\s+report(?:ing|s)?\b|\bad[-\s]?hoc\s+report(?:ing|s)?\b", re.I)),
    ("Reporting", re.compile(r"\breport(?:ing|s)?\b", re.I)),
    ("Data Analysis", re.compile(r"\bdata\s+analys(?:is|tics)\b|\banalytics?\b", re.I)),
    ("Data Handling", re.compile(r"\bdata\s+handling\b", re.I)),
    ("Problem Solving", re.compile(r"\bproblem\s+solving\b", re.I)),
    ("Communication", re.compile(r"\bcommunication\b|\bcommunicat(?:e|ed|ing|ion)\b|\bstakeholders?\b|\bclient\s+status\b|\bconferences?\b", re.I)),
    ("Presentation", re.compile(r"\bpresentation\b|\bstorytelling\b|\bpresent(?:ed|ing)?\b", re.I)),
    ("Attention To Detail", re.compile(r"\battention\s+to\s+detail\b|\bdetail-oriented\b|\bvalidation\b|\breconciliation\b", re.I)),
    ("Analytical Thinking", re.compile(r"\banalytical\s+(?:and\s+logical\s+)?thinking\b|\blogical\s+thinking\b|\banaly[sz](?:e|ed|ing)\b", re.I)),
]


def canonical_skill(skill):
    if not skill:
        return ""

    normalized = re.sub(r"[^\w\s\.\+#/-]", " ", str(skill).lower())
    normalized = re.sub(r"\s+", " ", normalized).strip()

    if normalized in SKILL_SYNONYMS:
        return SKILL_SYNONYMS[normalized]

    return " ".join(part.capitalize() for part in normalized.split())


def normalize_skill_list(skills):
    seen = set()
    result = []

    for skill in skills or []:
        canonical = canonical_skill(skill)
        key = canonical.lower()
        if canonical and key not in seen:
            seen.add(key)
            result.append(canonical)

    return _prune_overlapping_skills(result)


def _prune_overlapping_skills(skills):
    labels = {skill.lower() for skill in skills or []}
    remove = set()

    if "kpi reporting" in labels:
        remove.add("kpi")
    if any(label in labels for label in {"mis reporting", "kpi reporting", "business reporting"}):
        remove.add("reporting")
    if "data visualization" in labels:
        remove.add("dashboard")

    return [skill for skill in skills if skill.lower() not in remove]


def known_skills_in_text(value):
    found = []
    text = str(value or "")

    for label, pattern in KNOWN_SKILL_PATTERNS:
        if pattern.search(text):
            found.append(label)

    return normalize_skill_list(found)


def expand_skill_requirements(skills):
    expanded = []

    for skill in skills or []:
        known = known_skills_in_text(skill)
        expanded.extend(known or [canonical_skill(skill)])

    return normalize_skill_list(expanded)


def equivalent_skill(candidate_skill, required_skill):
    candidate = canonical_skill(candidate_skill)
    required = canonical_skill(required_skill)

    if not candidate or not required:
        return False

    if candidate.lower() == required.lower():
        return True

    for group in TRANSFERABLE_GROUPS:
        if candidate in group and required in group:
            return True

    return False


def category_map(skills):
    categories = {}
    for skill in normalize_skill_list(skills):
        category = SKILL_CATEGORIES.get(skill, "Other")
        categories.setdefault(category, []).append(skill)
    return categories


def normalize_designation(title):
    if not title:
        return ""

    title = re.sub(r"\s+", " ", str(title)).strip()
    title = re.sub(r"\bdev\b", "Developer", title, flags=re.I)
    title = re.sub(r"\bswe\b", "Software Engineer", title, flags=re.I)
    title = re.sub(r"\bml engineer\b", "Machine Learning Engineer", title, flags=re.I)

    return title
